---
title: "Investigating the impact of Hurricane Hugo on Stream Chemistry data in Luqillo"
subtitle: 'Alex Reed | Erica Bishop | Gabrielle Smith | Ruth Enriquez'
output: 
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      highlightStyle: style_duo_accent
      highlightLines: true
date: "2022-09-24"
---

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo_accent(
  primary_color = "#ffdfe5",
  secondary_color = "thistle",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Fira Mono"),
  text_font_size = 0.7
)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(plotly)
```

## Read in the Data

```{r, message = FALSE, warning = FALSE}
#read in raw data 
PRM <- read_csv(here('/courses/EDS214/gg_girls/raw_data',
                     'RioMameyesPuenteRoto.csv'))
BQ1 <- read_csv(here('/courses/EDS214/gg_girls/raw_data',
                     'QuebradaCuenca1-Bisley.csv'))
BQ2 <- read_csv(here('/courses/EDS214/gg_girls/raw_data',
                     'QuebradaCuenca2-Bisley.csv'))
BQ3 <- read_csv(here('/courses/EDS214/gg_girls/raw_data',
                     'QuebradaCuenca2-Bisley.csv'))
```

## Clean the Data

```{r}
#select data for relevant variables (data cleaning)
PRM_clean <- PRM %>% 
  select(Sample_Date, `NO3-N`, K, `NH4-N`, Sample_ID)
BQ1_clean <- BQ1 %>% 
  select(Sample_Date, `NO3-N`, K, `NH4-N`, Sample_ID)
BQ2_clean <- BQ2 %>% 
  select(Sample_Date, `NO3-N`, K, `NH4-N`, Sample_ID)
BQ3_clean <- BQ3 %>% 
  select(Sample_Date, `NO3-N`, K, `NH4-N`, Sample_ID) %>% 
  mutate(Sample_ID = "Q3")
  
```

---

## Join the Cleaned Data

```{r}
#joining cleaned data
Joined <- bind_rows(BQ1_clean, BQ2_clean, BQ3_clean, PRM_clean) 

#add month, year, and month-year columns to joined data
Joined <- Joined %>% 
  mutate(Year = lubridate::year(Sample_Date),
         Month = lubridate::month(Sample_Date),
         monthyear = zoo::as.yearmon(paste(Year, Month), "%Y %m")) 

#subset joined data to select for years 1989-1992
Joined_Sub <- Joined %>% 
  filter(Year >=1989 & Year <= 1994)
```

---

## Potassium Subset (1988-1994)

```{r}
#Potassium (subset) :
#add mean K values to joined subset data 
 Joined_Sub_K <- Joined_Sub %>% 
  group_by(monthyear, Sample_ID) %>% 
  mutate(meanK = mean(K, na.rm=TRUE)) %>% 
  select(Sample_ID, monthyear, meanK) %>% 
  distinct(monthyear, meanK)
```

---

##Potassium Subset Plot

```{r, warning = FALSE, fig.width=11, fig.height=4}
#Potassium (subset) :
#create a ggplot of subsetted data
K_subset <- ggplot(data=Joined_Sub_K, aes(x=monthyear, y=meanK)) + 
  geom_line(aes(color=Sample_ID, linetype=Sample_ID)) +
  theme(aspect.ratio = 1/3) + geom_vline(xintercept =1989.75)
ggplotly(K_subset)
```

---

## Nitrate Subset (1988-1994)

```{r}
#Nitrate (subset) :
#add mean N values to joined subset data 
 Joined_Sub_N <- Joined_Sub %>% 
  group_by(monthyear, Sample_ID) %>% 
  mutate(meanN = mean(`NO3-N`, na.rm=TRUE)) %>% 
  select(Sample_ID, monthyear, meanN) %>% 
  distinct(monthyear, meanN)
```

---

## Nitrate Subset Plot

```{r, warning=FALSE, fig.height=4, fig.width=11}
#Nitrate (subset) :
#create a ggplot of subsetted data
N_subset <- ggplot(data=Joined_Sub_N, aes(x=monthyear, y=meanN)) + 
  geom_line(aes(color=Sample_ID, linetype=Sample_ID)) +
  theme(aspect.ratio = 1/3)  + 
  geom_vline(xintercept = as.numeric(Joined$monthyear[38]))
ggplotly(N_subset)
```

---

## Potassium, Nitrate, and Ammonium Data (1986-2018)

```{r}
#Potassium, Nitrate, and Ammonium (all available years)

#add mean K and N values to joined data 
#(including data for all available years)
Joined <- Joined %>% 
  group_by(monthyear, Sample_ID) %>% 
  mutate(meanK = mean(K, na.rm=TRUE),
         meanN = mean(`NO3-N`, na.rm=TRUE),
         meanNH = mean(`NH4-N`, na.rm=TRUE)) %>% 
  select(Sample_ID, monthyear, meanK, meanN, meanNH) %>% 
  distinct(monthyear, meanK, meanN, meanNH)
```

---

## Potassium Plot (all years)

```{r, warning=FALSE, fig.height = 4, fig.width = 11}
#Potassium Plot (all available years)
#create a ggplot for all available data 
K_all <- ggplot(data=Joined, aes(x=monthyear, y=meanK)) + 
  geom_line(aes(color=Sample_ID, linetype=Sample_ID)) +
  theme(aspect.ratio = 1/3) + 
  geom_vline(xintercept = as.numeric(Joined$monthyear[38]))

ggplotly(K_all)
```

---

## Nitrate Plot (all years)

```{r, warning = FALSE, fig.height = 4, fig.width = 11}
#Nitrate Plot (all available years)
N_all <- ggplot(data=Joined, aes(x=monthyear, y=meanN)) + 
  geom_line(aes(color=Sample_ID, linetype=Sample_ID)) +
  theme(aspect.ratio = 1/3) + 
  geom_vline(xintercept = as.numeric(Joined$monthyear[38]))

ggplotly(N_all)
```

---

## Ammonium Plot (all years)

```{r, warning=FALSE, fig.height = 4, fig.width = 11}
#Ammonium Plot (all available years)
NH_all <- ggplot(data=Joined, aes(x=monthyear, y=meanNH)) + 
  geom_line(aes(color=Sample_ID, linetype=Sample_ID)) +
  theme(aspect.ratio = 1/3) + 
  geom_vline(xintercept = as.numeric(Joined$monthyear[38]))

ggplotly(NH_all)
```
